# Generated by Django 4.0.8 on 2024-02-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('scene_description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('acquisition_date', models.DateField()),
                ('acquisition_time', models.TimeField()),
                ('acquisition_by', models.CharField(max_length=200)),
                ('acquisition_tools', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('packaged_by', models.CharField(max_length=255)),
                ('transported_by', models.CharField(max_length=255)),
                ('examiner', models.CharField(max_length=255)),
                ('examination_tools', models.CharField(max_length=255)),
                ('examination_time', models.TimeField()),
                ('examination_date', models.DateField()),
                ('evidence_analysis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('TAR', 'Theft and Robbery'), ('B', 'Burglary'), ('PR', 'Offence against Property'), ('SO', 'Sexual offence'), ('MVO', 'Motor vehicle offence'), ('FD', 'Forced disappearance'), ('P', 'Piracy'), ('SS', 'Sexual slavery'), ('CL', 'Child labour'), ('DRC', 'Drug related case'), ('K', 'Kidnapping'), ('FI', 'False Imprisonment'), ('MC', 'Murder Case'), ('O', 'other')], max_length=3)),
                ('description', models.TextField()),
                ('reporter', models.CharField(max_length=200)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_letter', models.ImageField(upload_to='')),
                ('time_opened', models.DateTimeField(auto_now_add=True)),
                ('time_closed', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investigator')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigator.report')),
            ],
        ),
    ]
