# Generated by Django 4.0.8 on 2024-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='authorization_letter',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
