# Generated by Django 4.0.8 on 2024-02-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0002_alter_case_authorization_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='time_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
