# Generated by Django 4.0.8 on 2024-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0003_alter_case_time_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
