# Generated by Django 4.0.8 on 2024-02-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0005_report_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='investigator.case'),
        ),
    ]
