# Generated by Django 4.0.8 on 2024-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0006_evidence_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='examination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='examination_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='examination_tools',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='examiner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='packaged_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='packaging',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='transported_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
