# Generated by Django 4.0.8 on 2024-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0007_alter_evidence_evidence_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='serial_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
