# Generated by Django 4.0.8 on 2024-02-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0008_alter_evidence_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('VALID', 'VALID'), ('ACITVE', 'ACTIVE'), ('DISMISSED', 'DISMISSED')], default='VALID', max_length=10),
        ),
    ]
