# Generated by Django 4.0.8 on 2024-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0009_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='isdismissed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='isresolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
