# Generated by Django 4.0.8 on 2024-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TAR', 'Theft and Robbery'), ('B', 'Burglary'), ('PR', 'Offence against Property'), ('SO', 'Sexual offence'), ('MVO', 'Motor vehicle offence'), ('FD', 'Forced disappearance'), ('P', 'Piracy'), ('SS', 'Sexual slavery'), ('CL', 'Child labour'), ('DRC', 'Drug related case'), ('K', 'Kidnapping'), ('FI', 'False Imprisonment'), ('MC', 'Murder Case'), ('O', 'other')], max_length=3, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='investigator',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='accounts.specialization'),
        ),
    ]
