# Generated by Django 4.0.8 on 2024-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_category_specialization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='logo',
            field=models.ImageField(blank=True, default='static/images/evidence.jpg', null=True, upload_to=''),
        ),
    ]
